### ISSUE TITLE
Tracers are getting instrumented by HttpURLConnection plugin

### ISSUE THREAD

**Issue by hanwavefront** [opentracing-contrib/java-specialagent#381]
With v1.5.6 of the SpecialAgent, I'm seeing that the Wavefront and Jaeger tracers are getting instrumented by the agent.  Specifically, I'm seeing that the tracer reporters are getting instrumented with single-span traces like the following when creating an `HttpURLConnection`:

![image (1)](https://user-images.githubusercontent.com/41025882/73408762-27f1ee80-42b2-11ea-8fda-b17e735b744e.png)

With the Wavefront tracer plugin enabled for direct ingestion, I'm getting the following log messages:
```
-------> Intercept [wavefrontDirectSender-0] from: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [wavefrontDirectSender-0] from: public synchronized java.io.OutputStream sun.net.www.protocol.http.HttpURLConnection.getOutputStream() throws java.io.IOException
-------> Intercept [wavefrontDirectSender-0] from: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
```

With the Jaeger tracer plugin enabled, I'm getting the following log messages:
```
-------> Intercept [Timer-0] from: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [Timer-0] from: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
```

I realize that I can disable the HttpURLConnection instrumentation plugin, and it's certainly possible to blacklist these traces in the tracer implementations, but I'm wondering if there is a way to prevent the tracers from being instrumented by the agent?

**Comment by safris** [comment]
Hi @hanwavefront, thank you for submitting this issue. SpecialAgent should not be instrumenting tracers, so this is definitely a bug.

**Comment by safris** [comment]
Hi @hanwavefront, I have looked at this, and have figured out why this is happening.

**The Problem**

1. The `ByteBuddyManager` has [a clause](https://github.com/opentracing-contrib/java-specialagent/blob/860ab42378536a34afa13307c3be406b2d1aa793/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/ByteBuddyManager.java#L69-L70) that tells ByteBuddy to ignore `any()` classes in the `AgentRuleUtil.tracerClassLoader`. This clause makes it so that classes loaded in the class loader for the tracer plugin are not instrumented.
1. Though (1) takes care of all classes loaded in the tracer plugin's class loader, what about classes that are used by the tracer, but which are loaded in the bootstrap class loader (like `HttpURLConnection`). For this, we have another provision implemented in the [`MutexAgent`](https://github.com/opentracing-contrib/java-specialagent/blob/b15758a9a25b612fd4a93731df55b611f783eba8/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/MutexAgent.java). This agent performs a very simple thing: it instruments the OpenTracing API, and accounts for all API entries and exits. What does this give us? It allows us to know if an execution stack is coming from the OpenTracing API or not. In the `AgentRule` class, we have a method named [`isEnabled(String)`](https://github.com/opentracing-contrib/java-specialagent/blob/b15758a9a25b612fd4a93731df55b611f783eba8/opentracing-specialagent-api/src/main/java/io/opentracing/contrib/specialagent/AgentRule.java#L36-L42). As you can see, this method uses the same `latch` count that is handled by `MutexAgent` to see if the count is 0. If the latch count is _not 0_, then the execution is coming from an OpenTracing API, so the rule should not be triggered. If you check every agent rule implementation, you'll see a `isEnabled(origin)` condition.
1. The `MutexAgent` in (2) ensures rules are not triggered for executions coming from the OpenTracing API. There is, however, one more use-case that exists: What if the execution is coming from the tracer, but it is not stemming from the OpenTracing API. This can happen if the tracer does some async calls. If you look at the intercept logs you provided, the thread names are `wavefrontDirectSender-0` and `Timer-0`. These names seem to be indicative of async calls, and hence we have a problem.

(1) eliminates triggering on instances of classes that are loaded in the tracer's class loader.
(2) eliminates triggering on executions stemming from OpenTracing API calls.
(3) is a situation where the instance is of a class loaded in the bootstrap class loader (thus not handled by (1)), and since the class is async, the `latch` from `MutexAgent` is 0.

**Possible Solution**

In order to solve (3), SpecialAgent must know if a thread was started by the tracer. To get this information, we can instrument `Thread` to examine its most immediate caller class, and determine the class loader of this caller class. This gets more complicated when an `Executor` is used, so this solution would probably need to check the classes in the full tree of the entire stack trace. If any of the classes in the stack trace belong to the tracer's class loader, then this thread should be flagged to _not have any of its invocations instrumented._

If you have any thoughts or suggestions, I would love to hear your thoughts.

**Comment by safris** [comment]
Hi @hanwavefront, I have committed an implementation of the proposed solution. When [this build](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/643855311) finishes, please download [the development build](https://github.com/opentracing-contrib/java-specialagent#2112-development) and advise regarding your tests.

**Comment by hanwavefront** [comment]
Hi @safris , thank you for the quick response!  The build failed to finish, but I've built and tested your fix locally.  The fix makes sense to me, but unfortunately I'm still seeing the same traces for the Wavefront and Jaeger tracers.

For Wavefront, it seems that the `wavefrontdirectsender-0` thread is not triggering `ThreadMutexAgent.enter` (nor is it triggering `ThreadAgentRule.Start.enter`), even though I'm seeing the following in the logs:
```
-------> Intercept [wavefrontDirectSender-0] from: public synchronized void java.lang.Thread.start()
```
This thread is managed by an executor, and I'm seeing that the the executor's `Keep-Alive-Timer` thread is getting dropped:
```
-------> Intercept [Keep-Alive-Timer] DROP: public void jdk.internal.misc.InnocuousThread.run()
-------> Intercept [Keep-Alive-Timer] DROP: public void java.lang.Thread.run()
```
Other threads are indeed triggering `ThreadMutexAgent.enter`, so I'm not sure why this one is not.

For Jaeger, I'm also now seeing additional traces from the `java-thrift` plugin:
```
-------> Intercept [jaeger.RemoteReporter-QueueProcessor] from: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
```

Any idea what the cause might be?

**Comment by safris** [comment]
Hi @hanwavefront, I have updated the `ThreadMutexAgent`. Can you rebuild SpecialAgent on your system and run your tests again?

**Comment by hanwavefront** [comment]
Thanks @safris.  Still seeing the same behavior.  That method is not getting triggered by the thread in question.

**Comment by safris** [comment]
Hi @hanwavefront, in order to better understand what rule is resulting in what intercept, I've improved the logging as per #385. If you could, please re-pull, re-build, and re-run your test. The improved intercept logs will show what `AgentRule` subclass is responsible for each intercept.

**Comment by hanwavefront** [comment]
Sample of the logs with Wavefront tracer:
```
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [ThreadAgentRule@wavefrontDirectSender-0]: public synchronized void java.lang.Thread.start()
-------> Intercept [ThreadMutexAgent@wavefrontDirectSender-0]: public synchronized void java.lang.Thread.start()
-------> Intercept [ThreadAgentRule@Keep-Alive-Timer] DROP: public void jdk.internal.misc.InnocuousThread.run()
-------> Intercept [ThreadAgentRule@Keep-Alive-Timer] DROP: public void java.lang.Thread.run()
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.OutputStream sun.net.www.protocol.http.HttpURLConnection.getOutputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.OutputStream sun.net.www.protocol.http.HttpURLConnection.getOutputStream() throws java.io.IOException
```
So it looks like `ThreadMutexAgent` is intercepting `wavefrontDirectSender-0` but a different thread is being added to `tracerThreadIds`, resulting in `wavefrontDirectSender-0` continuing to get instrumented.  I believe it's because `Thread.currentThread()` in `isEnabled()` is different from `Thread thiz` in `ThreadMutexAgent.enter()`.  `thiz` in this case is actually `Keep-Alive-Timer`, which is why `Keep-Alive-Timer` ends up getting dropped, as seen in the logs.

For Jaeger tracer, I think the behavior is similar with `Timer-0`.  But there's also `jaeger.RemoteReporter-QueueProcessor` which doesn't seem to get intercepted by `ThreadMutexAgent`:
```
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
...
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
...
-------> Intercept [ThreadAgentRule@Timer-0]: public synchronized void java.lang.Thread.start()
-------> Intercept [ThreadMutexAgent@Timer-0]: public synchronized void java.lang.Thread.start()
-------> Intercept [ThreadAgentRule@Keep-Alive-Timer] DROP: public void jdk.internal.misc.InnocuousThread.run()
-------> Intercept [ThreadAgentRule@Keep-Alive-Timer] DROP: public void java.lang.Thread.run()
...
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [ThriftProtocolAgentRule@jaeger.RemoteReporter-QueueProcessor]: public void org.apache.thrift.protocol.TCompactProtocol.writeFieldStop() throws org.apache.thrift.TException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public void sun.net.www.protocol.http.HttpURLConnection.connect() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@Timer-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [ThriftAgentRule@jaeger.RemoteReporter-QueueProcessor]: public org.apache.thrift.protocol.TProtocol org.apache.thrift.protocol.TCompactProtocol$Factory.getProtocol(org.apache.thrift.transport.TTransport)
```

**Comment by safris** [comment]
Hi @hanwavefront, after reviewing the implementation of [`ThreadMutexAgent`](https://github.com/opentracing-contrib/java-specialagent/blob/3e2636a28e232481bd7e0b0ed47c2ec2fa678672/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/ThreadMutexAgent.java#L51-L67), it seems to be correct to me. In `ThreadMutexAgent`, `thiz` refers to the new thread that is being started, and `Thread.currentThread()` refers to the parent thread from which the new thread is being started. If you review your logs with this in mind, you will realize that it should be working.

However, it is clearly not working. I believe the reason for this is that the `wavefrontDirectSender-0` and `jaeger.RemoteReporter-QueueProcessor` threads are pooled threads that were started via `ExecutorService`. Conceptually, the operation resulting in the initialization of the thread pool from the original invoking thread of the `ExecutorService` should itself be handled by the `ThreadMutexAgent`, but we are not seeing this.

I have revised the `ThreadMutexAgent` to also intercept `Thread::new`, as it should be true (correct me if I'm wrong) that if the thread that instantiates a new thread is excluded from instrumentation, then the new thread should also be excluded from instrumentation.

**Comment by safris** [comment]
@hanwavefront, I had to disable the `OnConstructor` facet of `ThreadMutexAgent`. It seems the `Thread::new` rule is intercepting threads that shouldn't be intercepted. I believe we'll need something akin:
```
builder.ignore(new AgentBuilder.RawMatcher.ForElementMatchers(nameStartsWith("net.bytebuddy.").or(isSynthetic()), any(), any()))
```

**Comment by hanwavefront** [comment]
Hi @safris, with the latest updates I'm seeing intercepts of the constructor as expected but I'm still not seeing the thread being excluded:

```-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [ThreadMutexAgent@wavefrontDirectSender-0]: private java.lang.Thread(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long,java.security.AccessControlContext,boolean)
-------> Intercept [ThreadMutexAgent@wavefrontDirectSender-0]: public java.lang.Thread(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,long,boolean)
-------> Intercept [ThreadMutexAgent@wavefrontDirectSender-0]: private jdk.internal.misc.InnocuousThread(java.lang.ThreadGroup,java.lang.Runnable,java.lang.String,java.lang.ClassLoader)
-------> Intercept [ThreadAgentRule@wavefrontDirectSender-0]: public synchronized void java.lang.Thread.start()
-------> Intercept [ThreadAgentRule@Keep-Alive-Timer] DROP: public void jdk.internal.misc.InnocuousThread.run()
-------> Intercept [ThreadAgentRule@Keep-Alive-Timer] DROP: public void java.lang.Thread.run()
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException
-------> Intercept [HttpURLConnectionAgentRule@wavefrontDirectSender-0]: public synchronized java.io.InputStream sun.net.www.protocol.http.HttpURLConnection.getInputStream() throws java.io.IOException```

Will investigate further.

**Comment by hanwavefront** [comment]
I think these threads have already been created and started by the time instrumentation begins.  I logged the thread ids from `ThreadMutexAgent` locally and saw that the intercepted thread ids start in the 20s and go up from there, but the `wavefrontDirectSender-0` thread that never gets intercepted has an id of 13.

I don't know if there's a way to ensure that instrumentation starts before these threads are created.  But adding the class loader check to `AgentRule::isEnabled` should ensure that threads that were already alive get checked.

**Comment by safris** [comment]
Hi @hanwavefront, this is a good observation. However, your suggestion will not work:

> But adding the class loader check to `AgentRule::isEnabled` should ensure that threads that were already alive get checked as well.

Each thread's stack trace starts with `Thread.run()`, and the question we want to answer is: "was the execution stack _that led_ to `Thread.start()` stemmed from the tracer's class loader?" When `AgentRule::isEnabled` is called, we only have visibility into the current thread -- i.e. only the current thread's execution stack. The only way to answer this question is to capture the moment where `Thread.start()` is called, which gives us visibility into the execution stack we desire to investigate. Furthermore, if a parent thread is enabled for instrumentation (i.e. the main thread, for instance), it doesn't mean all of its child threads should be enabled for instrumentation. This is true because all threads have their ancestor parent as the main thread. Some execution stacks will cross into the tracer's class loader, and some will not. Therefore, we can deduce the following:
1. If a parent thread is marked as "enabled for instrumentation", then at each `Thread.start()` stemming from this thread, we need to investigate the execution stack that led to this `Thread.start()` of the new child thread.
1. If a parent thread is marked as "not enabled for instrumentation", then it is safe to mark each of its child threads also as "not enabled for instrumentation" (please correct me if I'm wrong here -- the question we need to answer is: would it be possible for any child thread created/started from the tracer to qualify for instrumentation -- i.e. is it possible that such a child thread could be used by some other thread that _is qualified for instrumentation_ -- I think the answer to this question is "no", and if this assumption is wrong, then the risk is that we'd be incorrectly marking some threads as "not enabled for instrumentation" when they really should be enabled for instrumentation).

**Comment by hanwavefront** [comment]
> 2. If a parent thread is marked as "not enabled for instrumentation", then it is safe to mark each of its child threads also as "not enabled for instrumentation" (please correct me if I'm wrong here -- the question we need to answer is: would it be possible for any child thread created/started from the tracer to qualify for instrumentation -- i.e. is it possible that such a child thread could be used by some other thread that _is qualified for instrumentation_ -- I think the answer to this question is "no", and if this assumption is wrong, then the risk is that we'd be incorrectly marking some threads as "not enabled for instrumentation" when they really should be enabled for instrumentation).

I agree, I can't think of a situation where a child thread of the tracer would be used by a thread that is qualified for instrumentation.

**Comment by hanwavefront** [comment]
Which is why I am thinking that if there is an additional check for the current thread in `AgentRule::isEnabled`, checking whether its execution stack stemmed from tracer's class loader, it would be able to filter out threads that were started by the tracer before `ThreadMutexAgent` was loaded.  If we do this, we'd be able to remove `ThreadMutexAgent` since it would be redundant. My thinking is that checking the execution stack while the thread is running would be no different than checking the execution stack when the thread is started since the thread is only going to be used by the tracer.  But let me know if I am mistaken.

**Comment by safris** [comment]
@hanwavefront, if do:

```
class Foo {
  public static void main(String[] args) {
    new Thread("bar") {
      public void run() {
        new Exception().printStackTrace();
      }
    }.start();
  }
}
```

You will get:

```
java.lang.Exception
	at Foo.run(Foo.java:?)
	at Foo.run(Foo.java:?)
```

As you can see, the call stack for thread "bar" starts at `Thread.run()`, but what we need to know is the call stack that led to `Thread.start()`, which happens in `Foo.main()`.

**Comment by safris** [comment]
@hanwavefront, I reimplemented the the approach with a novel solution that uses `InheritableThreadLocal` and does not require instrumentation. For this approach to work, it is necessary to load the `AgentRule` class before any threads are started from the "main" thread. For this, I created `AgentRule.loadThreadInstrumentable()`, which is called before `SpecialAgent.loadTracer()`. I also implemented [ThreadLineageTest](https://github.com/opentracing-contrib/java-specialagent/blob/4b2de661196dba62413192c4ecdcd2718a0e46a9/opentracing-specialagent-api/src/test/java/io/opentracing/contrib/specialagent/ThreadLineageTest.java) to validate the behavior we desire. This test shows that a thread's lineage can be recorded and used to determine whether a class qualifies for instrumentation or not. Please let me know your results!

**Comment by hanwavefront** [comment]
Thanks @safris!  Trying it out and seeing NPEs in `AgentRule::isEnabled`:

```
Exception in thread "process reaper" java.lang.NullPointerException
	at io.opentracing.contrib.specialagent.AgentRule.isEnabled(AgentRule.java:80)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by safris** [comment]
Hi @hanwavefront, I've fixed the NPEs, which were causing the integration tests to fail. The [latest build](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/647043708) has succeeded.

**Comment by hanwavefront** [comment]
Hi @safris.  I do see `isThreadInstrumentable` warnings for `process reaper` and for `Keep-Alive-Timer` (which is created by `KeepAliveCache` because of the tracer using HTTP keep-alive).  Nevertheless, the agent is no longer instrumenting `wavefrontDirectSender-0` and `jaeger.RemoteReporter-QueueProcessor`, and everything in my test app is working and getting instrumented as I would expect.  Thank you for fixing!

**Comment by safris** [comment]
Hi @hanwavefront, this is very good news to hear! Thanks for posting this issue, cause it presented a real and present problem that needed to be fixed. Closing this issue.
